# Generated by Django 5.2.1 on 2025-06-07 22:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRSyncConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='FHIR server base URL')),
                ('timeout', models.IntegerField(default=30, help_text='Request timeout in seconds')),
                ('retry_attempts', models.IntegerField(default=3)),
                ('retry_delay', models.IntegerField(default=5, help_text='Delay between retries in seconds')),
                ('is_active', models.BooleanField(default=True)),
                ('auth_type', models.CharField(choices=[('none', 'No Authentication'), ('basic', 'Basic Auth'), ('bearer', 'Bearer Token'), ('oauth2', 'OAuth2')], default='none', max_length=20)),
                ('auth_credentials', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FHIR Sync Configuration',
                'verbose_name_plural': 'FHIR Sync Configurations',
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='create', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=100, help_text='Lower numbers = higher priority')),
                ('fhir_data', models.JSONField(help_text='FHIR resource JSON')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fhir_id', models.CharField(blank=True, help_text='ID returned by FHIR server', max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Sync Queue Item',
                'verbose_name_plural': 'Sync Queue Items',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('queue_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Fsync.syncqueue')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SyncRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Patient', 'Patient'), ('Practitioner', 'Practitioner'), ('Encounter', 'Encounter'), ('Observation', 'Observation'), ('Condition', 'Condition'), ('MedicationStatement', 'MedicationStatement'), ('AllergyIntolerance', 'AllergyIntolerance'), ('Procedure', 'Procedure'), ('Immunization', 'Immunization'), ('DocumentReference', 'DocumentReference')], max_length=50)),
                ('hms_model_app', models.CharField(help_text='Django app name', max_length=100)),
                ('hms_model_name', models.CharField(help_text='Django model name', max_length=100)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sync_frequency', models.CharField(choices=[('manual', 'Manual Only'), ('realtime', 'Real-time'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='manual', max_length=20)),
                ('sync_filter', models.JSONField(blank=True, default=dict, help_text='Django ORM filter conditions')),
                ('field_mappings', models.JSONField(blank=True, default=dict, help_text='Custom field mappings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sync Rule',
                'verbose_name_plural': 'Sync Rules',
                'unique_together': {('resource_type', 'hms_model_app', 'hms_model_name')},
            },
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='sync_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Fsync.syncrule'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['status', 'priority'], name='Fsync_syncq_status_9223e2_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['resource_type', 'status'], name='Fsync_syncq_resourc_4e8664_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['scheduled_at'], name='Fsync_syncq_schedul_ddc8ea_idx'),
        ),
    ]
