# Generated by Django 5.2.1 on 2025-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fsync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncqueue',
            name='field_mapping_used',
            field=models.JSONField(blank=True, default=dict, help_text='Field mappings used for this sync'),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='transform_applied',
            field=models.JSONField(blank=True, default=dict, help_text='Transformations applied'),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='validation_results',
            field=models.JSONField(blank=True, default=dict, help_text='Validation results'),
        ),
        migrations.AddField(
            model_name='syncrule',
            name='default_patient_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Default Patient field mappings'),
        ),
        migrations.AddField(
            model_name='syncrule',
            name='transform_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Field transformation rules'),
        ),
        migrations.AddField(
            model_name='syncrule',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Data validation rules before sync'),
        ),
        migrations.AlterField(
            model_name='syncrule',
            name='field_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Custom field mappings from HMS to FHIR'),
        ),
    ]
