# Generated by Django 5.1.7 on 2025-04-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='encounter',
        ),
        migrations.AlterField(
            model_name='observation',
            name='code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='observation',
            name='unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='observation',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
