# Generated by Django 5.2.1 on 2025-08-12 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='fhir_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('corrected', 'Corrected'), ('cancelled', 'Cancelled'), ('entered-in-error', 'Entered in Error')], default='final', max_length=20),
        ),
        migrations.AlterField(
            model_name='observation',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MedicalRecords.encounter'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
