# Generated by Django 5.1.7 on 2025-04-20 17:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0002_remove_observation_encounter_alter_observation_code_and_more'),
        ('Patients', '0009_remove_encounter_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='encounter',
            field=models.ForeignKey(default=342, on_delete=django.db.models.deletion.CASCADE, to='MedicalRecords.encounter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encounter',
            name='encounter_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 17, 14, 23, 116319, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encounter',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient'),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='reason',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
