# Generated by Django 5.2.1 on 2025-08-16 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0002_observation_fhir_id_observation_last_sync_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentReference',
        ),
    ]
