# Generated by Django 5.2 on 2025-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalRecords', '0003_observation_encounter_alter_encounter_encounter_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='reason',
            field=models.TextField(),
        ),
    ]
