# Generated by Django 5.2 on 2025-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fhir_sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingsyncqueue',
            name='resource_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Practitioner', 'Practitioner'), ('Encounter', 'Encounter'), ('Observation', 'Observation'), ('Condition', 'Condition'), ('MedicationStatement', 'MedicationStatement'), ('AllergyIntolerance', 'AllergyIntolerance'), ('Procedure', 'Procedure'), ('Immunization', 'Immunization'), ('DocumentReference', 'DocumentReference')], max_length=50),
        ),
    ]
