# Generated by Django 5.1.7 on 2025-04-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
        ('Practitioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='Practitioner.practitioner'),
        ),
    ]
