# Generated by Django 5.2.1 on 2025-06-28 13:54

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
