# Generated by Django 5.2.1 on 2025-06-10 12:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fhirsynctask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['family_name', 'given_name']},
        ),
        migrations.AddField(
            model_name='fhirsynctask',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if sync failed', null=True),
        ),
        migrations.AddField(
            model_name='fhirsynctask',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether this patient record is active'),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line1',
            field=models.CharField(blank=True, help_text='Street address', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address_line2',
            field=models.CharField(blank=True, help_text='Apartment, suite, etc.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='Known allergies (comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='country',
            field=models.CharField(default='Ghana', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='deceased_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Last name/surname', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='fhir_id',
            field=models.CharField(blank=True, help_text='FHIR server patient ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='given_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='First name(s)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(blank=True, help_text='Insurance ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Last FHIR sync timestamp', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated'), ('unknown', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, help_text='MRN', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, help_text='Middle name(s)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_prefix',
            field=models.CharField(blank=True, help_text='Dr., Mr., Mrs., etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='name_suffix',
            field=models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('tw', 'Twi'), ('ga', 'Ga'), ('ee', 'Ewe'), ('fr', 'French'), ('ha', 'Hausa')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='patient',
            name='registration_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='patient',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='patient',
            name='state_province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_arrived',
            field=models.DateField(blank=True, help_text='Last visit date', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, help_text='Full name (legacy field)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, help_text='National ID/SSN', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(help_text='Internal patient identifier', max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='fhirsynctask',
            index=models.Index(fields=['resource_type', 'status'], name='Patients_fh_resourc_e5e9d3_idx'),
        ),
        migrations.AddIndex(
            model_name='fhirsynctask',
            index=models.Index(fields=['created_at'], name='Patients_fh_created_709e75_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['family_name', 'given_name'], name='patients_family__8bd755_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['birth_date'], name='patients_birth_d_8b9243_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id'], name='patients_nationa_c07601_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['medical_record_number'], name='patients_medical_f25f99_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['primary_phone'], name='patients_primary_3e4ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_arrived'], name='patients_last_ar_2c61d9_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['active'], name='patients_active_e8f3b6_idx'),
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
