# Generated by Django 5.1.7 on 2025-04-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Patient', 'Patient'), ('Practitioner', 'Practitioner'), ('Encounter', 'Encounter'), ('Observation', 'Observation')], max_length=50)),
                ('resource_id', models.CharField(max_length=100)),
                ('json_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practitioner_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('technician', 'Technician'), ('admin', 'Admin')], max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hospital_affiliation', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encounter_id', models.CharField(max_length=100, unique=True)),
                ('encounter_type', models.CharField(choices=[('inpatient', 'Inpatient'), ('outpatient', 'Outpatient'), ('emergency', 'Emergency'), ('telehealth', 'Telehealth')], max_length=50)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_id', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('vital-signs', 'Vital Signs'), ('laboratory', 'Laboratory'), ('imaging', 'Imaging'), ('social-history', 'Social History'), ('diagnostic', 'Diagnostic')], max_length=50)),
                ('observation_type', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.encounter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.AutoField(primary_key=True, serialize=False)),
                ('recorded_date', models.DateTimeField(blank=True, null=True)),
                ('diagnosis', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=100, null=True)),
                ('clinical_status', models.CharField(blank=True, max_length=100, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=100, null=True)),
                ('onset', models.CharField(blank=True, max_length=255, null=True)),
                ('abatement', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('medications', models.TextField(blank=True, null=True)),
                ('test_results', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.encounter')),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.practitioner')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Scheduled', 'Scheduled'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patients.patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Patients.practitioner')),
            ],
        ),
    ]
