# Generated by Django 5.2.1 on 2025-06-28 13:54

import django.core.validators
import encrypted_model_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0002_alter_fhirsynctask_options_alter_patient_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_family__8bd755_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_nationa_c07601_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_medical_f25f99_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patients_primary_3e4ee5_idx',
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_line1',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Street address', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address_line2',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Apartment, suite, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, help_text='Known allergies (comma-separated)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_type',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_relationship',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='family_name',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='Last name/surname'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='given_name',
            field=encrypted_model_fields.fields.EncryptedCharField(help_text='First name(s)'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Insurance ID', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_record_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='MRN', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='middle_name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Middle name(s)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Full name (legacy field)', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name_prefix',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Dr., Mr., Mrs., etc.', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name_suffix',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Jr., Sr., III, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='National ID/SSN', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postal_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='primary_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='secondary_phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state_province',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['patient_id'], name='patients_patient_e63b14_idx'),
        ),
    ]
