# Generated by Django 5.1.7 on 2025-04-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0002_alter_appointment_practitioner'),
        ('Patients', '0002_pendingsyncqueue_practitioner_encounter_observation_and_more'),
        ('Practitioner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Practitioner.practitioner'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='practitioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Practitioner.practitioner'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='recorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Practitioner.practitioner'),
        ),
        migrations.DeleteModel(
            name='Practitioner',
        ),
    ]
