# Generated by Django 5.1.7 on 2025-04-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0003_alter_encounter_practitioner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='practitioner',
        ),
        migrations.DeleteModel(
            name='PendingSyncQueue',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
