# Generated by Django 5.1.7 on 2025-04-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0004_remove_appointment_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHIRSyncTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(default='Patient', max_length=100)),
                ('resource_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
