# Generated by Django 5.1.7 on 2025-04-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0005_fhirsynctask'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhirsynctask',
            name='synced_adatet',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
