# Generated by Django 5.1.7 on 2025-04-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0006_fhirsynctask_synced_adatet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fhirsynctask',
            old_name='synced_adatet',
            new_name='synced_at',
        ),
    ]
