# Generated by Django 5.1.7 on 2025-04-17 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0007_rename_synced_adatet_fhirsynctask_synced_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='Patients.patient'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='Patients.patient'),
        ),
    ]
