# Generated by Django 5.1.7 on 2025-04-20 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patients', '0008_alter_condition_patient_alter_observation_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='practitioner',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='encounter',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
        migrations.DeleteModel(
            name='Encounter',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
    ]
