# Generated by Django 5.2.1 on 2025-08-20 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Practitioner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='practitioner',
            old_name='hospital_affiliation',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='practitioner',
            name='role',
        ),
        migrations.AddField(
            model_name='practitioner',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practitioner',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('technician', 'Technician'), ('admin', 'Admin'), ('IT', 'IT')], default='doctor', max_length=50),
            preserve_default=False,
        ),
    ]
